name: cryptox
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.4
  flutter_slidable: ^0.6.0
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.15
  intl_phone_number_input: ^0.7.0+2
  flutter_spinkit: ^5.1.0
  clipboard: ^0.1.3
  local_auth: ^1.1.11
  flutter_launcher_icons: ^0.11.0
  flutter_cache_manager: ^3.3.0
  platform: ^3.1.0
  retrofit: ^3.0.1+1
  sqflite: ^2.0.3
  path: ^1.8.1
  skeletons: ^0.0.3
  web_socket_channel: ^2.2.0
  #webviewx: ^0.2.1
  #dio: ^4.0.6
  #dio: ^5.0.0
  #flutter_inappwebview: ^5.7.1
  url_launcher: ^6.1.10
  video_compress: ^3.0.0
  video_player: ^2.4.6
  flutter_overlay_loader: ^2.0.0
  #flutter_svg: ^1.1.6
  flutter_svg: ^2.0.7
  rxdart: ^0.27.5
  carousel_slider: ^4.1.1
  number_paginator: ^0.2.3
  image_picker: ^0.8.4+11
  image_picker_android: 0.8.4+13
  flutter_typeahead: ^4.0.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  dropdown_button2: ^2.3.9
  marquee: ^2.2.3
  firebase_messaging: ^12.0.3
  flutter_local_notifications: ^9.8.0+1
  firebase_core: ^1.21.0
  in_app_review: ^2.0.6
  file: ^6.1.4
  intl_phone_field: ^3.2.0

  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_otp_text_field: ^1.1.3+2
  permission_handler: ^11.0.0
  intl: ^0.17.0
  #retrofit: '>=4.0.0 <5.0.0'
  #retrofit: ^4.1.0
  package_info_plus: ^4.1.0
  pretty_dio_logger:
  shimmer: ^3.0.0
  webview_flutter: ^4.4.2
  flutter_share: ^2.0.0
  cached_network_image: ^3.3.0
  android_play_install_referrer: ^0.3.0
  control_style: ^0.1.0
  uni_links: ^0.5.0
  firebase_crashlytics: ^2.9.0
  google_sign_in: ^6.1.6
  http: any
  googleapis_auth: any
  firebase_remote_config: any
  upgrader: any
  connectivity_plus: any
  internet_connection_checker_plus: any
  font_awesome_flutter: ^10.5.0
  json_annotation: ^4.9.0 # Ensure this is at least version 4.9.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  package_info_plus: any
  #retrofit_generator: '>=5.0.0 <6.0.0'
  #retrofit_generator: ^8.1.0
  build_runner: ^2.1.7
  json_serializable: ^6.0.1

dependency_overrides:
  firebase_core_platform_interface: 4.5.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Images/AppIcon.png"

module:
  androidX: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Images/
    - assets/icon/
    - assets/icon/primary-color/
    - assets/icon/grey/
    - assets/user/
    - assets/crypto_icon/
    - assets/slider/
    - assets/svg/
    - assets/lottie/
#    - assets/index.html
#    - assets/charting_library/
#    - assets/datafeeds/
#    - assets/charting_library/bundles/
#    - assets/datafeeds/udf/dist/bundle.js

  fonts:
    - family: poppins
      fonts:
        - asset: fonts/poppinsregular.ttf
        - asset: fonts/poppinslight.ttf
        - asset: fonts/poppinsmedium.ttf
        - asset: fonts/poppinsthin.ttf
        - asset: fonts/poppinssemibold.ttf
        - asset: fonts/poppinsbold.ttf
        - asset: fonts/poppinsextrabold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Regular.ttf
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-Light.ttf
          weight: 300
