// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'UserDetail.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserDetail _$UserDetailFromJson(Map<String, dynamic> json) => UserDetail(
      profilePic: json['profilePic'] as String?,
      branchName: json['branchName'] as String?,
      commRate: (json['commRate'] as num?)?.toDouble(),
      aadhar: json['aadhar'] as String?,
      pan: json['pan'] as String?,
      gstin: json['gstin'] as String?,
      address: json['address'] as String?,
      userID: (json['userID'] as num?)?.toInt(),
      mobileNo: json['mobileNo'] as String?,
      name: json['name'] as String?,
      outletName: json['outletName'] as String?,
      emailID: json['emailID'] as String?,
      isGSTApplicable: json['isGSTApplicable'] as bool?,
      isTDSApplicable: json['isTDSApplicable'] as bool?,
      isCCFGstApplicable: json['isCCFGstApplicable'] as bool?,
      pincode: json['pincode'] as String?,
      dob: json['dob'] as String?,
      shopType: json['shopType'] as String?,
      qualification: json['qualification'] as String?,
      poupulation: json['poupulation'] as String?,
      locationType: json['locationType'] as String?,
      landmark: json['landmark'] as String?,
      alternateMobile: json['alternateMobile'] as String?,
      bankName: json['bankName'] as String?,
      ifsc: json['ifsc'] as String?,
      accountNumber: json['accountNumber'] as String?,
      accountName: json['accountName'] as String?,
      ekycid: (json['ekycid'] as num?)?.toInt(),
      stateID: (json['stateID'] as num?)?.toInt(),
      kycStatus: (json['kycStatus'] as num?)?.toInt(),
      loginID: (json['loginID'] as num?)?.toInt(),
      lt: (json['lt'] as num?)?.toInt(),
      city: json['city'] as String?,
      stateName: json['stateName'] as String?,
      roles: (json['roles'] as List<dynamic>?)
          ?.map((e) => ChildRoles.fromJson(e as Map<String, dynamic>))
          .toList(),
      slabs: json['slabs'] as String?,
      states: json['states'] as String?,
      ip: json['ip'] as String?,
      browser: json['browser'] as String?,
      resultCode: (json['resultCode'] as num?)?.toInt(),
      msg: json['msg'] as String?,
      roleID: (json['roleID'] as num?)?.toInt(),
      role: json['role'] as String?,
      referalID: (json['referalID'] as num?)?.toInt(),
      slabID: (json['slabID'] as num?)?.toInt(),
      isVirtual: json['isVirtual'] as bool?,
      isWebsite: json['isWebsite'] as bool?,
      isAdminDefined: json['isAdminDefined'] as bool?,
      isSurchargeGST: json['isSurchargeGST'] as bool?,
      prefix: json['prefix'] as String?,
      outletID: (json['outletID'] as num?)?.toInt(),
      wid: (json['wid'] as num?)?.toInt(),
      isDoubleFactor: json['isDoubleFactor'] as bool?,
      regDate: json['regDate'] as String?,
      activationDate: json['activationDate'] as String?,
      isRealAPI: json['isRealAPI'] as bool?,
      isTopup: (json['isTopup'] as num?)?.toInt(),
      rank: json['rank'] == null
          ? null
          : UserDetailRank.fromJson(json['rank'] as Map<String, dynamic>),
      isMobileVerified: json['isMobileVerified'] as bool?,
      isEmailVerified: json['isEmailVerified'] as bool?,
      isRenewalRequired: json['isRenewalRequired'] as bool?,
      isGoogle2FAEnable: json['isGoogle2FAEnable'] as bool?,
      isGoogle2FARegister: json['isGoogle2FARegister'] as bool?,
      toupAmount: (json['toupAmount'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$UserDetailToJson(UserDetail instance) =>
    <String, dynamic>{
      'profilePic': instance.profilePic,
      'branchName': instance.branchName,
      'commRate': instance.commRate,
      'aadhar': instance.aadhar,
      'pan': instance.pan,
      'gstin': instance.gstin,
      'address': instance.address,
      'userID': instance.userID,
      'mobileNo': instance.mobileNo,
      'name': instance.name,
      'outletName': instance.outletName,
      'emailID': instance.emailID,
      'isGSTApplicable': instance.isGSTApplicable,
      'isTDSApplicable': instance.isTDSApplicable,
      'isCCFGstApplicable': instance.isCCFGstApplicable,
      'pincode': instance.pincode,
      'dob': instance.dob,
      'shopType': instance.shopType,
      'qualification': instance.qualification,
      'poupulation': instance.poupulation,
      'locationType': instance.locationType,
      'landmark': instance.landmark,
      'alternateMobile': instance.alternateMobile,
      'bankName': instance.bankName,
      'ifsc': instance.ifsc,
      'accountNumber': instance.accountNumber,
      'accountName': instance.accountName,
      'ekycid': instance.ekycid,
      'stateID': instance.stateID,
      'kycStatus': instance.kycStatus,
      'loginID': instance.loginID,
      'lt': instance.lt,
      'city': instance.city,
      'stateName': instance.stateName,
      'roles': instance.roles,
      'slabs': instance.slabs,
      'states': instance.states,
      'ip': instance.ip,
      'browser': instance.browser,
      'resultCode': instance.resultCode,
      'msg': instance.msg,
      'roleID': instance.roleID,
      'role': instance.role,
      'referalID': instance.referalID,
      'slabID': instance.slabID,
      'isVirtual': instance.isVirtual,
      'isWebsite': instance.isWebsite,
      'isAdminDefined': instance.isAdminDefined,
      'isSurchargeGST': instance.isSurchargeGST,
      'prefix': instance.prefix,
      'outletID': instance.outletID,
      'wid': instance.wid,
      'isDoubleFactor': instance.isDoubleFactor,
      'regDate': instance.regDate,
      'activationDate': instance.activationDate,
      'isRealAPI': instance.isRealAPI,
      'isTopup': instance.isTopup,
      'rank': instance.rank,
      'isMobileVerified': instance.isMobileVerified,
      'isEmailVerified': instance.isEmailVerified,
      'isRenewalRequired': instance.isRenewalRequired,
      'isGoogle2FAEnable': instance.isGoogle2FAEnable,
      'isGoogle2FARegister': instance.isGoogle2FARegister,
      'toupAmount': instance.toupAmount,
    };
