// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'SendMoneyBankReport.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SendMoneyBankReport _$SendMoneyBankReportFromJson(Map<String, dynamic> json) =>
    SendMoneyBankReport(
      intType: (json['_Type'] as num?)?.toInt(),
      type_: json['type_'] as String?,
      refundStatus: (json['refundStatus'] as num?)?.toInt(),
      refundStatus_: json['refundStatus_'] as String?,
      opening: (json['opening'] as num?)?.toDouble(),
      outletUserMobile: json['outletUserMobile'] as String?,
      outletUserCompany: json['outletUserCompany'] as String?,
      senderMobile: json['senderMobile'] as String?,
      groupID: json['groupID'] as String?,
      ccf: (json['ccf'] as num?)?.toDouble(),
      surcharge: (json['surcharge'] as num?)?.toDouble(),
      refundGST: (json['refundGST'] as num?)?.toDouble(),
      amtWithTDS: (json['amtWithTDS'] as num?)?.toDouble(),
      creditedAmount: (json['credited_Amount'] as num?)?.toDouble(),
      ccName: json['ccName'] as String?,
      ccMobileNo: json['ccMobileNo'] as String?,
      serviceID: (json['_ServiceID'] as num?)?.toInt(),
      tid: (json['tid'] as num?)?.toInt(),
      transactionID: json['transactionID'] as String?,
      userID: (json['userID'] as num?)?.toInt(),
      outletNo: json['outletNo'] as String?,
      outlet: json['outlet'] as String?,
      account: json['account'] as String?,
      oid: (json['oid'] as num?)?.toInt(),
      operator: json['operator'] as String?,
      lastBalance: (json['lastBalance'] as num?)?.toDouble(),
      requestedAmount: (json['requestedAmount'] as num?)?.toDouble(),
      amount: (json['amount'] as num?)?.toDouble(),
      balance: (json['balance'] as num?)?.toDouble(),
      slabCommType: json['slabCommType'] as String?,
      commission: (json['commission'] as num?)?.toDouble(),
      entryDate: json['entryDate'] as String?,
      api: json['api'] as String?,
      liveID: json['liveID'] as String?,
      vendorID: json['vendorID'] as String?,
      apiRequestID: json['apiRequestID'] as String?,
      modifyDate: json['modifyDate'] as String?,
      optional1: json['optional1'] as String?,
      optional2: json['optional2'] as String?,
      optional3: json['optional3'] as String?,
      optional4: json['optional4'] as String?,
      display1: json['display1'] as String?,
      display2: json['display2'] as String?,
      display3: json['display3'] as String?,
      display4: json['display4'] as String?,
      switchingName: json['switchingName'] as String?,
      circleName: json['circleName'] as String?,
      isWTR: json['isWTR'] as bool?,
      commType: json['commType'] as bool?,
      gstAmount: (json['gstAmount'] as num?)?.toDouble(),
      tdsAmount: (json['tdsAmount'] as num?)?.toDouble(),
      customerNo: json['customerNo'] as String?,
      ccMobile: json['ccMobile'] as String?,
      apiCode: json['apiCode'] as String?,
      requestMode: json['requestMode'] as String?,
    );

Map<String, dynamic> _$SendMoneyBankReportToJson(
        SendMoneyBankReport instance) =>
    <String, dynamic>{
      '_Type': instance.intType,
      'type_': instance.type_,
      'refundStatus': instance.refundStatus,
      'refundStatus_': instance.refundStatus_,
      'opening': instance.opening,
      'outletUserMobile': instance.outletUserMobile,
      'outletUserCompany': instance.outletUserCompany,
      'senderMobile': instance.senderMobile,
      'groupID': instance.groupID,
      'ccf': instance.ccf,
      'surcharge': instance.surcharge,
      'refundGST': instance.refundGST,
      'amtWithTDS': instance.amtWithTDS,
      'credited_Amount': instance.creditedAmount,
      'ccName': instance.ccName,
      'ccMobileNo': instance.ccMobileNo,
      '_ServiceID': instance.serviceID,
      'tid': instance.tid,
      'transactionID': instance.transactionID,
      'userID': instance.userID,
      'outletNo': instance.outletNo,
      'outlet': instance.outlet,
      'account': instance.account,
      'oid': instance.oid,
      'operator': instance.operator,
      'lastBalance': instance.lastBalance,
      'requestedAmount': instance.requestedAmount,
      'amount': instance.amount,
      'balance': instance.balance,
      'slabCommType': instance.slabCommType,
      'commission': instance.commission,
      'entryDate': instance.entryDate,
      'api': instance.api,
      'liveID': instance.liveID,
      'vendorID': instance.vendorID,
      'apiRequestID': instance.apiRequestID,
      'modifyDate': instance.modifyDate,
      'optional1': instance.optional1,
      'optional2': instance.optional2,
      'optional3': instance.optional3,
      'optional4': instance.optional4,
      'display1': instance.display1,
      'display2': instance.display2,
      'display3': instance.display3,
      'display4': instance.display4,
      'switchingName': instance.switchingName,
      'circleName': instance.circleName,
      'isWTR': instance.isWTR,
      'commType': instance.commType,
      'gstAmount': instance.gstAmount,
      'tdsAmount': instance.tdsAmount,
      'customerNo': instance.customerNo,
      'ccMobile': instance.ccMobile,
      'apiCode': instance.apiCode,
      'requestMode': instance.requestMode,
    };
